Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecTool.py", line 813, in submit
    if any(char in changes[3] for char in ('"',"'"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\SpecDB.py", line 93, in ModifyEntry
    cur.execute("UPDATE spec SET doc='"+str(changes[3])+"', text='"+str(parseSpecs(changes[3]).replace("'","''").replace('"','""')) +"', modTime='"+str(os.path.getmtime(changes[3]))+"' WHERE doc='"+entry[3]+"'")
sqlite3.OperationalError: near ".": syntax error
