Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\BudgetingTool.py", line 276, in formatFile
    if 'qty' in hDict: sheetNew[("B"+str(rowNum))] = data[i][hDict['qty']]
                                          ^^^^^^^^^^^^
KeyError: 'qty'
