Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\BulkLoads.py", line 442, in form
    formatFile(voltList)
  File "C:\Users\Antonio\Documents\GitHub\SDI_Tools\BulkLoads.py", line 197, in formatFile
    if type(rowData[indexDict['VOLTS']]) == list or type(rowData[indexDict['PH']]) == list or type(rowData[indexDict['AMPS']]) == list:
                    ~~~~~~~~~^^^^^^^^^
KeyError: 'VOLTS'
